name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-anon-usage=0.4.4
  - archspec=0.2.3
  - asttokens=2.4.1
  - blas=1.0
  - boltons=23.0.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.2.2
  - conda=24.5.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - console_shortcut_miniconda=0.1.1
  - contourpy=1.2.0
  - cryptography=42.0.5
  - cycler=0.11.0
  - debugpy=1.8.2
  - decorator=5.1.1
  - distro=1.9.0
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - fmt=9.1.0
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozendict=2.4.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=58.2
  - idna=3.7
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lcms2=2.12
  - lerc=3.0
  - libarchive=3.6.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libcurl=8.7.1
  - libdeflate=1.17
  - libexpat=2.6.2
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.16
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libogg=1.3.5
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - menuinst=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.3.1
  - packaging=23.2
  - pandas=2.2.2
  - parso=0.8.4
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - powershell_shortcut_miniconda=0.0.1
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pure_eval=0.2.2
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.18.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2024.1
  - pywin32=306
  - pyzmq=26.0.3
  - qt-main=5.15.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.2
  - ruamel.yaml=0.17.21
  - seaborn=0.13.2
  - setuptools=69.5.1
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - truststore=0.8.0
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - vc=14.2
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
